In [1]:
import pandas as pd
import numpy as np
#from pandas import read_excel 
#from pandas import ExcelFile
#from scipy import stats
import matplotlib.pyplot as plt
import math
import xlwt
import openpyxl

In [2]:
#change to the name you put in JohnCode
filename = 'GCFID-trc-tet-RBS-library-May2022.xlsx'

In [3]:
wb = openpyxl.load_workbook(filename)
sheet1 = ''
sheet1 = wb['John_Code']
sheet2 = ''
sheet2 = wb.create_sheet('Peak_ID')

In [4]:
df = pd.read_excel(filename, sheet_name = 'John_Code', header = None)


#Preparing list of strings called Vial_names where each element is the name of a sample

Vial_names = []
Standard_names = ['FaOH-10','FaOH-50','FaOH-100','FaOH-500']
Sample_names = ['A1-A','A1-B','A2-A','A2-B','A3-A','A3-B','A4-A','A4-B','A5-A','A5-B','A6-A','A6-B','CM24-A','CM24-B','F1-A','F1-B','F2-A','F2-B','F3-A','F3-B','F4-A','F4-B','F5-A','F5-B','trc-tet-A','trc-tet-B']
#Control_names = ['Neg','WT']

#for x in Control_names:
#    vial1 = x + '-1'
#    Vial_names.append(vial1)
#    vial2 = x + '-2'
#    Vial_names.append(vial2)
#    vial3 = x + '-3'
#    Vial_names.append(vial3)
    
for x in Standard_names:
    Vial_names.append(x)
    
for x in Sample_names:
    Vial_names.append(x)

In [5]:
df

            0       1       2       3      4       5
0     FaOH-10     NaN     NaN     NaN    NaN     NaN
1       Peak#  R.Time  I.Time  F.Time   Area  Height
2           1   1.378   1.343   1.423   2603    1063
3           2   1.442   1.423   1.507   1331     327
4           3   1.636   1.507   1.662  34856    6957
...       ...     ...     ...     ...    ...     ...
1310       41  26.178  26.136  26.235   2228     838
1311       42  26.371   26.33  26.399   1508     752
1312       43  26.706  26.632  26.726   1681     565
1313       44  26.863  26.772    26.9   3792    1635
1314       45   26.95    26.9  26.964   1033     323

[1315 rows x 6 columns]

In [6]:
# FAOH Retention Times (minutes on FatWax column w Stabilwax protocol)


C3 = 4.080
C4 = 7.645
C5 = 12.622
C6 = 14.872
C7 = 16.310
C8 = 17.613
C9 = 18.648
C10 = 19.667
C11 = 20.660
C12 = 21.550
C13 = 22.340
C14 = 23.170
C15 = 23.920
C16 = 24.709
C17 = 25.464
C18 = 26.127

# Create a dictionary which can be updated by changing values above. The dictionary will be called in peak identification (next block)

RT_dict = {'C3': C3, 'C4': C4, 'C5': C5, 'C6': C6, 'C7': C7, 'C8': C8, 'C9': C9, 'C10': C10, 'C11': C11, 'C12': C12, 'C13': C13, 'C14': C14, 'C15': C15, 'C16': C16, 'C17': C17, 'C18': C18}

# Create list of analytes to make it easy to call dictionary in future
analytes = ['C3','C4','C5','C6','C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'C17','C18']

In [7]:
# This block goes through the dataframe from the John_Code sheet and picks out sample names and relevant peaks.

num_rows = len(df)
row_name = list(range(0, num_rows))
txt_file_headers = ['R.time', 'I.time', 'F.time', 'Area', 'Height','Peak_ID']

for i in row_name:                
    if i < num_rows+1: 
        # picks out each row in dataframe and truncates - would be more elegant to not have to use dataframe but whatever
        row_calling = df.loc[i,:]
        vals = row_calling.values.tolist()
        vals = vals[0:6]
        
        y = type(vals[0])
        
        if vals[0] in Vial_names:
            sample_of_interest = 'yes'
        
            # picks out sample names and adds to worksheet
            print(vals[0])
            heading = [vals[0],vals[0],vals[0],vals[0],vals[0],vals[0]]
            print(heading)
            sheet2.append(heading)
            sheet2.append(txt_file_headers)

        elif vals[0] != 'Peak#' and y == str:
            sample_of_interest = 'no'
            
                
        # picks out peaks
        x = type(vals[1])
        if x == int: # This if statement is for the rare occasion when the retention time of an analyte is an integer
            vals[1] = float(vals[1])
            x = type(vals[1])
            
        if x == float and sample_of_interest == 'yes':
            for a in analytes:
                upper_tolerance = RT_dict[a] + 0.1
                lower_tolerance = RT_dict[a] - 0.1
                if vals[1] < upper_tolerance and vals[1] > lower_tolerance:
                    #print(vals[1])
                    vals.append(a)
                    #print(vals)
                    sheet2.append(vals[1:])

FaOH-10
['FaOH-10', 'FaOH-10', 'FaOH-10', 'FaOH-10', 'FaOH-10', 'FaOH-10']
A6-B
['A6-B', 'A6-B', 'A6-B', 'A6-B', 'A6-B', 'A6-B']
A4-A
['A4-A', 'A4-A', 'A4-A', 'A4-A', 'A4-A', 'A4-A']
A6-A
['A6-A', 'A6-A', 'A6-A', 'A6-A', 'A6-A', 'A6-A']
A4-B
['A4-B', 'A4-B', 'A4-B', 'A4-B', 'A4-B', 'A4-B']
A2-A
['A2-A', 'A2-A', 'A2-A', 'A2-A', 'A2-A', 'A2-A']
A2-B
['A2-B', 'A2-B', 'A2-B', 'A2-B', 'A2-B', 'A2-B']
trc-tet-A
['trc-tet-A', 'trc-tet-A', 'trc-tet-A', 'trc-tet-A', 'trc-tet-A', 'trc-tet-A']
A5-B
['A5-B', 'A5-B', 'A5-B', 'A5-B', 'A5-B', 'A5-B']
trc-tet-B
['trc-tet-B', 'trc-tet-B', 'trc-tet-B', 'trc-tet-B', 'trc-tet-B', 'trc-tet-B']
A5-A
['A5-A', 'A5-A', 'A5-A', 'A5-A', 'A5-A', 'A5-A']
A1-A
['A1-A', 'A1-A', 'A1-A', 'A1-A', 'A1-A', 'A1-A']
A3-B
['A3-B', 'A3-B', 'A3-B', 'A3-B', 'A3-B', 'A3-B']
A1-B
['A1-B', 'A1-B', 'A1-B', 'A1-B', 'A1-B', 'A1-B']
A3-A
['A3-A', 'A3-A', 'A3-A', 'A3-A', 'A3-A', 'A3-A']
F5-B
['F5-B', 'F5-B', 'F5-B', 'F5-B', 'F5-B', 'F5-B']
FaOH-50
['FaOH-50', 'FaOH-50', 'FaOH-50', 'FaOH-50', 'FaOH-50', 'FaOH-50']
F5-A
['F5-A', 'F5-A', 'F5-A', 'F5-A', 'F5-A', 'F5-A']
F1-A
['F1-A', 'F1-A', 'F1-A', 'F1-A', 'F1-A', 'F1-A']
CM24-B
['CM24-B', 'CM24-B', 'CM24-B', 'CM24-B', 'CM24-B', 'CM24-B']
F3-B
['F3-B', 'F3-B', 'F3-B', 'F3-B', 'F3-B', 'F3-B']
F1-B
['F1-B', 'F1-B', 'F1-B', 'F1-B', 'F1-B', 'F1-B']
CM24-A
['CM24-A', 'CM24-A', 'CM24-A', 'CM24-A', 'CM24-A', 'CM24-A']
F3-A
['F3-A', 'F3-A', 'F3-A', 'F3-A', 'F3-A', 'F3-A']
F4-A
['F4-A', 'F4-A', 'F4-A', 'F4-A', 'F4-A', 'F4-A']
FaOH-100
['FaOH-100', 'FaOH-100', 'FaOH-100', 'FaOH-100', 'FaOH-100', 'FaOH-100']
F4-B
['F4-B', 'F4-B', 'F4-B', 'F4-B', 'F4-B', 'F4-B']
FaOH-500
['FaOH-500', 'FaOH-500', 'FaOH-500', 'FaOH-500', 'FaOH-500', 'FaOH-500']
F2-A
['F2-A', 'F2-A', 'F2-A', 'F2-A', 'F2-A', 'F2-A']
F2-B
['F2-B', 'F2-B', 'F2-B', 'F2-B', 'F2-B', 'F2-B']

In [8]:
wb.save(filename)

In [9]:
#Now remove duplicate peaks from Peak_ID tab

In [10]:
wb = openpyxl.load_workbook(filename)
sheet2 = ''
sheet2 = wb['Peak_ID']
sheet3 = ''
sheet3 = wb.create_sheet('Quantification w IS,ES')

In [11]:
ID  = 'blank'
Area = 'blank'
sheet3_list = []

for row in sheet2.iter_rows(min_row = 1, max_row = 5000, min_col = 1, max_col = 10, values_only = True): # iterates through a semi-arbitrary number of rows and only reports values, still a tuple
    
    if row[5] == ID: # If there is a duplicate label for a single peak, pick the peak with the larger area
        if row[3] > Area:
            sheet3_list.pop()
            sheet3_list.append(row)
        else:
            continue
            
    else:
        sheet3_list.append(row)
    
    if row[3] == None: # breaks out of for loop once all text file data is iterated through
        break
    
    else:
        ID = row[5]
        Area = row[3]
            
for row in sheet3_list:
    sheet3.append(row)
    
#Notice that this code may not work as intended if there is a duplicate in the first row, however, since the first row will always be a sample name, it is fine.

In [12]:
wb.save(filename)

In [13]:
wb = openpyxl.load_workbook(filename)
sheet_read = ''
sheet_read = wb['Peak_ID']
sheet3 = ''
sheet3 = wb.create_sheet('Quantification w IS,ES-full')

In [14]:
sample_header=[]
data_header = ['R.time', 'I.time', 'F.time', 'Area', 'Height','Peak_ID']

for row in sheet_read.iter_rows(min_row = 1, max_row = sheet_read.max_row, min_col = 1, max_col = 10, values_only = True): # iterates through a semi-arbitrary number of rows and only reports values, still a tuple
    if row[0] == row[1] and row [1] == row[2]: # This is a bit clunky, but it ensures the order of the samples in the Peak_ID tab is maintained
        sample = row[0]
        sample_header = [sample, sample, sample, sample, sample, sample]
        sheet3.append(sample_header)
        sheet3.append(data_header)
        for a in analytes:
            blank_row = [0,0,0,0,0,a]
            sheet3.append(blank_row)

In [15]:
print(sheet3.max_row)

540

In [16]:
#wb = openpyxl.load_workbook('GCData-JGI_ACRs.xlsx')
sheet2 = ''
sheet2 = wb['Quantification w IS,ES']
sheet3 = ''
sheet3 = wb['Quantification w IS,ES-full']

In [17]:
Ass_Fat = True
last_count = 1
while Ass_Fat:
    
    counter = 0
    
    for row2, row3 in zip(sheet2.iter_rows(min_row = 1, max_row = sheet3.max_row, min_col = 1, max_col = 10, values_only = True), sheet3.iter_rows(min_row = 1, max_row = sheet3.max_row, min_col = 1, max_col = 10, values_only = True)):
        #print(row1[0], row2[0])
        counter = counter + 1
        #print(counter)
        if counter < last_count:
            continue
        elif row2[5] == row3[5]:
            last_count = counter
            print(last_count)
        elif row2[5] != row3[5]:
            #print(row3[5])
            sheet2.insert_rows(counter)
            sheet2.cell(row = counter, column = 6).value = row3[5]
            sheet2.cell(row = counter, column = 5).value = 0.000000001
            #last_count = counter
            break

        if counter == sheet3.max_row:
            Ass_Fat = False
            break
        else:
            continue

1
2
2
3
3
4
5
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
21
22
23
23
24
25
25
26
27
27
28
29
29
30
31
31
32
33
33
34
35
35
36
37
38
39
40
41
41
42
43
44
45
46
47
48
49
50
51
52
53
53
54
55
56
57
57
58
59
59
60
61
61
62
63
63
64
65
66
67
67
68
69
69
70
71
71
72
73
74
75
75
76
77
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
111
112
113
113
114
115
115
116
117
118
119
120
121
121
122
123
123
124
125
125
126
127
128
128
129
129
130
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
147
148
149
149
150
151
151
152
153
153
154
155
156
157
157
158
159
159
160
161
162
163
164
164
165
165
166
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
183
184
185
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
290
291
291
292
293
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
326
327
327
328
328
329
329
330
331
331
332
333
334
335
336
337
338
339
340
341
342
343
344
344
345
345
346
346
347
347
348
349
349
350
350
351
352
353
354
354
355
355
356
356
357
357
358
359
359
360
361
362
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
380
381
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
398
399
399
400
400
401
401
402
403
403
404
404
405
405
406
407
408
408
409
409
410
410
411
411
412
413
413
414
415
416
416
417
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
452
453
453
454
455
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
488
489
489
490
491
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
506
507
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
524
525
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540

In [18]:
#wb.remove_sheet('Quantification w IS,ES-full')
wb.save(filename)

In [19]:
for i, j in zip([1,2,3], [3,2,1]):
    print(i, j)

1 3
2 2
3 1